In [12]:
#Knowing about the array:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)

print(arr)

print(arr.data) #Address of the first element 
print(arr.shape) #Dimentions of the array
print(arr.dtype) #datatype
print(arr.strides) #Size per block

print("----------------------------------")
li = [[1,2,3,4],[5,6,7,8]]
arr = np.array(li)
print(arr)
print(arr.data) #Address of the first element 
print(arr.shape) #Dimentions of the array
print(arr.dtype) #datatype
print(arr.strides) #Size per block

[1 2 3 4 5]
(5,)
int64
(8,)
----------------------------------
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int64
(32, 8)


In [25]:
#Slicing in 2d Numpy:
li = [[1,2,3,4,] , [5,6,7,8] , [9,10,11,12] , [13,14,15,16]]
arr = np.array(li)
print(arr)
print("----------------------------------")
#If I write : li[0:3][3] : Error : As li[0:3] = [[1,2,3,4,] , [5,6,7,8] , [9,10,11,12]]
#But in Numpy :
print(arr[0:3 , 3]) #Note here arr[0:3][3] will not work. 
print("----------------------------------")
print(arr[3][0:3]) #This works
print("----------------------------------")
print(arr[2:4 , 2:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------------------------------
[ 4  8 12]
----------------------------------
[13 14 15]
----------------------------------
[[11 12]
 [15 16]]


In [32]:
#Reshape fucntion:
arr=np.arange(1,21,1)
arr=arr.reshape(4,5)
print(arr)
print(type(arr))
print((arr[0:3 , 0:4]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [61]:
#Adding one to all elements of numpy arr:
arr = np.arange(1,5,1)
print(arr)
arr = arr + 1
print(arr)

[1 2 3 4]
[2 3 4 5]


In [67]:
#Performing arthematic operations on 2 numpy array : 
a = np.arange(1,5,1)
b = np.arange(1,9,2)
print("a : ",a)
print("b : ",b)
c = a+b
print(c)
c = b-a
print(c)
c = a*b
print(c)
c = b/a
print(c)
c = a**b
print(c)

a :  [1 2 3 4]
b :  [1 3 5 7]
[ 2  5  8 11]
[0 1 2 3]
[ 1  6 15 28]
[1.         1.5        1.66666667 1.75      ]
[    1     8   243 16384]


In [76]:
#Some usefull inbuilt functions:
arr = np.arange(1,5,1)
print(arr)
print("Min element : ",arr.min()) #Returns the minimum element
print("Min element index : ",arr.argmin()) #Returns the index of the minimum number
print("Max element : ",arr.max())
print("Max element index : ",arr.argmax())
print("sum : " , arr.sum())
print("Mean : " , arr.mean())

[1 2 3 4]
Min element :  1
Min element index :  0
Max element :  4
Max element index :  3
sum :  10
Mean :  2.5


In [85]:
#Relational operations on Numpy arrays:
arr1 = np.array([7,16,14,20,24])
arr2 = np.array([12,16,11,14,16])
print("arr1 > arr2 :",arr1 > arr2)
print("arr1 < arr2 :",arr1 < arr2)
print("arr1 == arr2 :",arr1 == arr2)
#Also we can compare with a scalar:
print("arr > 15 : ",arr1 > 15)

arr1 > arr2 : [False False  True  True  True]
arr1 < arr2 : [ True False False False False]
arr1 == arr2 : [False  True False False False]
arr > 15 :  [False  True False  True  True]


In [87]:
#Logical operations:
arr1 = np.array([True,False,True,False])
arr2 = np.array([True,True,False,False])
print("OR : ",np.logical_or(arr1 , arr2))
print("AND : ",np.logical_and(arr1 , arr2))
print("NOT : ",np.logical_not(arr1))

OR :  [ True  True  True False]
AND :  [ True False False False]
NOT :  [False  True False  True]


In [96]:
#Boolean indexing:
arr = np.array([7,16,14,20,24])
print(arr > 10)
#To obtain only those element which satify a condition:
arrWithCondition = arr[arr>10]
print(arrWithCondition)
#Also we can update only some specific values by using this:
arr[arr>15] += 2 #Adding to to only those elements that are > 15
print(arr)
#To get the indexes where our condition is satisfied:
ind = np.where(arr>15) 
print("indexes of satifing condition : " , ind)
#Now we can use these indexes to seperate elements of other array:
a = np.array(['a' , 'b' , 'c' , 'd' , 'e' , 'f'])
print(a[ind])

[False  True  True  True  True]
[16 14 20 24]
[ 7 18 14 22 26]
indexes of satifing condition :  (array([1, 3, 4]),)
['b' 'd' 'e']


In [3]:
#Boolean indexing for 2D arrays:
import numpy as np
arr = np.random.randint(1,30 , (5,6))
print("Array is: \n",arr)
boolArr = arr>20
print(boolArr)
a = arr[boolArr]
print("Printing arr>20 by passing boolArr: ",a)
#Upadating in arr:
arr[boolArr] = 100
print(arr)
#Now say we want to make some changes according to some condition but Only in 1 column (say 3) of the array.
boolArr = (arr[: , 3]==100)
print(boolArr)
#Now to print arr:
arr[boolArr , 3] = 500 #used boolArr as row index as row is changing and column = 3.
print(arr)

Array is: 
 [[24 20  6  5  3  5]
 [19 26 25 10 25 16]
 [ 8 20 29  3 29 10]
 [16  3 16 16 14 13]
 [25 20 16  9 24 25]]
[[ True False False False False False]
 [False  True  True False  True False]
 [False False  True False  True False]
 [False False False False False False]
 [ True False False False  True  True]]
Printing arr>20 by passing boolArr:  [24 26 25 25 29 29 25 24 25]
[[100  20   6   5   3   5]
 [ 19 100 100  10 100  16]
 [  8  20 100   3 100  10]
 [ 16   3  16  16  14  13]
 [100  20  16   9 100 100]]
[False False False False False]
[[100  20   6   5   3   5]
 [ 19 100 100  10 100  16]
 [  8  20 100   3 100  10]
 [ 16   3  16  16  14  13]
 [100  20  16   9 100 100]]


In [26]:
#Broadcasting : For array with unequal dimentions
#Now if dimention of 2 arrays are equal we can do element by element operations 
#So 3,3 and 3,2 are not compatible But 3,3 and 1,3 are compatible
arr1 = np.random.randint(1,5,(3,3))
arr2 = np.random.randint(1,5,3)
print("arr1 : \n" , arr1)
print("arr2 : \n" , arr2)
ans = arr1+arr2
print("arr1 + arr2 : \n",ans) # 1,3 sized array is added to each row of 3,3 array
print("----------------------------------")
arr2 = np.random.randint(1,5,(3,1))
print("arr1 : \n" , arr1)
print("arr2 : \n" , arr2)
ans = arr1+arr2
print("arr1 + arr2 : \n",ans) # 3,1 sized array is added to each column of 3,3 array
print("----------------------------------")
arr1 = np.array([1,2,3])
arr2 = np.array([[100],[200],[300]])
print("arr1 : \n",arr1)
print("arr2 : \n",arr2)
#Now see how broadcasting works here:
ans = arr1+arr2
print("arr1 + arr2 : \n",ans)

arr1 : 
 [[1 4 2]
 [1 1 2]
 [4 1 4]]
arr2 : 
 [4 2 2]
arr1 + arr2 : 
 [[5 6 4]
 [5 3 4]
 [8 3 6]]
----------------------------------
arr1 : 
 [[1 4 2]
 [1 1 2]
 [4 1 4]]
arr2 : 
 [[2]
 [3]
 [1]]
arr1 + arr2 : 
 [[3 6 4]
 [4 4 5]
 [5 2 5]]
----------------------------------
arr1 : 
 [1 2 3]
arr2 : 
 [[100]
 [200]
 [300]]
arr1 + arr2 : 
 [[101 102 103]
 [201 202 203]
 [301 302 303]]


In [13]:
#Transpose an array : Use np.transpose() : Take a matrix and returns it's transpose
arr = np.random.randint(1,10,(3,2))
print(arr)
arr = np.transpose(arr)
print(arr)

[[1 5]
 [8 7]
 [5 4]]
[[1 8 5]
 [5 7 4]]


In [15]:
#resize() :
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:') 
print(a)
print()

print('The shape of first array:') 
print(a.shape) 
print()  
b = np.resize(a, (3,2)) 

print('Second array:') 
print(b) 
print()  

print('The shape of second array:') 
print(b.shape)
print()  
# Observe that first row of a is repeated in b since size is bigger 

print('Resize the second array:') 
b = np.resize(a,(3,3)) 
print(b)

First array:
[[1 2 3]
 [4 5 6]]

The shape of first array:
(2, 3)

Second array:
[[1 2]
 [3 4]
 [5 6]]

The shape of second array:
(3, 2)

Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [21]:
#reshape():
a = np.arange(8)
print('The original array:')
print(a)
print()

b = a.reshape(4,2) #The number of elements must be the same : (4,2) and (1,8)
print('The modified array:')
print(b)

The original array:
[0 1 2 3 4 5 6 7]

The modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
