# NumPy:

In [10]:
import numpy as np
#numpy can have homogeneous elements only
#Creating numpy array : np.array() : Argument(Mandatory) : Array like objest ->List
list1 = [1,2,3]
nArray1 = np.array(list1)
print(list1)
print(nArray1)
print(type(nArray1))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>


In [15]:
#Another argument that can be passes into the array() fucntion : dtype = int (This is the type of numpy array we want)
list2 = [1,2,4.5]
nArray2 = np.array(list2)
print(list2)
print(nArray2)
print(type(nArray2))
nArray2 = np.array(list2 , dtype = int)
print(nArray2)
print(type(nArray2))
print(len(nArray2))

[1, 2, 4.5]
[1.  2.  4.5]
<class 'numpy.ndarray'>
[1 2 4]
<class 'numpy.ndarray'>
3


In [32]:
#More fucntions to create a numpy array:
arr = np.ones(3)
print(arr)
arr = np.zeros(3,dtype = int)
print(arr)
#These can be used to create 2D arrays by passing a tuple as the first argument. Tuple is the dimentions of the array.
print("------------------")
arr = np.ones((2,3) , dtype = int)
print(arr)
print("------------------")
arr = np.ones((3,3) , dtype = str)
print(arr)
print("------------------")
arr = np.zeros((3,3) , dtype = str) #zeros give '' on dtype = str
print(arr)
#Full fucntion : generic for 0,1 and all values:
print("------------------")
arr = np.full(3,5) #Minimum 2 arguments are compulsary
print(arr)
print(type(arr[0]))
print("------------------")
arr = np.full((4,5),5,dtype = float) #in full() default data type is int (Not float : unlike ones and zeros)
print(arr)
print("------------------")
arr = np.empty(3) # empty() function gives non initialsied values : Random. Rest all same : Deafult float
print(arr)
print(type(arr[0]))

[1. 1. 1.]
[0 0 0]
------------------
[[1 1 1]
 [1 1 1]]
------------------
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
------------------
[['' '' '']
 ['' '' '']
 ['' '' '']]
------------------
[5 5 5]
<class 'numpy.int64'>
------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
------------------
[2.5e-323 2.5e-323 2.5e-323]
<class 'numpy.float64'>


In [49]:
#More ways to create numpy array : Evenly spaced values
#np.arange() : 4 arguments : startValue , endValue (exclusive) , step , dType. Only endValue is compulsary. startValue default=0
arr = np.arange(5)
print(arr)
print("------------------")
#np.linspace() : start , stop(inclusive) , Number of samples(default = 50) , dtype , endpoint = False/True(default)
arr = np.linspace(2,10)
print(arr)
print("Step value is : ",(arr[1]-arr[0]))
print("Step value is : ",(arr[2]-arr[1]))
print("------------------")
arr = np.linspace(2 , 10 , endpoint = False)
print(arr)
print("Step value is : ",(arr[1]-arr[0]))
print("Step value is : ",(arr[2]-arr[1]))
print("------------------")
arr = np.linspace(2,10,10)
print(arr)
arr = np.linspace(2,10,10,dtype = int)
print(arr)

[0 1 2 3 4]
------------------
[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
Step value is :  0.16326530612244916
Step value is :  0.16326530612244872
------------------
[2.   2.16 2.32 2.48 2.64 2.8  2.96 3.12 3.28 3.44 3.6  3.76 3.92 4.08
 4.24 4.4  4.56 4.72 4.88 5.04 5.2  5.36 5.52 5.68 5.84 6.   6.16 6.32
 6.48 6.64 6.8  6.96 7.12 7.28 7.44 7.6  7.76 7.92 8.08 8.24 8.4  8.56
 8.72 8.88 9.04 9.2  9.36 9.52 9.68 9.84]
Step value i

In [53]:
#Creating identity matrix:
arr = np.identity(3,dtype = int) #Only 1 argument for size (dtype can be used)
print(arr)
print("------------------")
arr = np.eye(3,4) #Can take 1 or 2 arguments for size for a matrix of mXn (dtype can be used)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [63]:
#Creating array with random values:
arr = np.random.rand(2) #Generates array of size 2 and values between 0 to 1 : 0 to n can be obtained by multipling by n
#in rand() dtype can't be used
#Also if no argument is passed we get 1 random integer between 0 and 1 
print(arr)
print("------------------")
arr = np.random.randint(40,50,(6,7)) #Arrguments: minValue , maxValue(Mandatory) , size(by default returns a random integer)
print(arr)

[0.22413527 0.25236635]
------------------
[[47 47 47 42 47 40 42]
 [44 46 45 42 47 43 47]
 [45 48 40 44 44 40 46]
 [42 41 45 46 40 41 48]
 [46 46 47 42 48 41 44]
 [42 48 47 42 49 42 40]]
