In [28]:
import numpy as np
import csv
ob = open("year2017.csv")
data = csv.DictReader(ob , skipinitialspace = True) 
killed = []
country = []
wounded = []

for row in data:
    killed.append(row["Killed"])
    country.append(row["Country"])
    wounded.append(row["Wounded"])
killedArr = np.array(killed)
#At this point we have lot of missing values.So we can't convert it to float:
killedArr[killedArr == ''] = '0.0'
#Here killedArr == '' creates a boolean array and then the values at those boolean array are changed = '0.0'
#Now to convert it into float array (from string)
killedArr = np.array(killedArr , dtype = float)
print(killedArr)

#Same for wounded 
woundedArr = np.array(wounded)
woundedArr[woundedArr == ''] = '0.0'
woundedArr = np.array(woundedArr , dtype = float)
print(woundedArr)

total_Killed_and_wounded = killedArr + woundedArr
print(total_Killed_and_wounded )

[0. 2. 7. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 2. 7. ... 0. 0. 0.]
